/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMemoryEater */

#ifndef _Included_NativeMemoryEater
#define _Included_NativeMemoryEater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMemoryEater
 * Method:    eatMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMemoryEater_eatMemory
  (JNIEnv *, jobject);

/*
 * Class:     NativeMemoryEater
 * Method:    freeMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMemoryEater_freeMemory
  (JNIEnv *, jobject);

/*
 * Class:     NativeMemoryEater
 * Method:    getEater
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMemoryEater_getEater
  (JNIEnv *, jobject);

/*
 * Class:     NativeMemoryEater
 * Method:    destroyEater
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMemoryEater_destroyEater
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
